# Generated by Django 5.2.14 on 2026-05-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial_contacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Звернення', 'verbose_name_plural': 'Звернення'},
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='message',
            field=models.TextField(verbose_name='Повідомлення'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Ім’я'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='subject',
            field=models.CharField(choices=[('general', 'Загальне питання'), ('product', 'Питання щодо товару'), ('partnership', 'Партнерство'), ('vacancy', 'Вакансія')], default='general', max_length=20, verbose_name='Тема'),
        ),
    ]
