# Generated by Django 5.2.15 on 2026-06-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contactrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Inquiries', 'verbose_name_plural': 'Inquiries'},
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Read'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='subject',
            field=models.CharField(choices=[('general', 'General inquiry'), ('product', 'Product inquiry'), ('partnership', 'Partnership'), ('vacancy', 'Vacancy')], default='general', max_length=20, verbose_name='Subject'),
        ),
    ]
