# Generated by Django 5.2.14 on 2026-05-16 21:18

import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Должность")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=300, unique=True, verbose_name="Slug"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                (
                    "description",
                    django_summernote.fields.SummernoteTextField(
                        verbose_name="Описание"
                    ),
                ),
                (
                    "requirements",
                    django_summernote.fields.SummernoteTextField(
                        blank=True, verbose_name="Требования"
                    ),
                ),
                (
                    "conditions",
                    django_summernote.fields.SummernoteTextField(
                        blank=True, verbose_name="Условия"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "is_urgent",
                    models.BooleanField(default=False, verbose_name="Срочная"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Вакансия",
                "verbose_name_plural": "Вакансии",
                "ordering": ["-is_urgent", "-created_at"],
            },
        ),
    ]
