# Generated by Django 5.2.14 on 2026-05-18 19:08

import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial_vacancies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-is_urgent', '-created_at'], 'verbose_name': 'Вакансія', 'verbose_name_plural': 'Вакансії'},
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='conditions',
            field=django_summernote.fields.SummernoteTextField(blank=True, verbose_name='Умови'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=django_summernote.fields.SummernoteTextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='Термінова'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=django_summernote.fields.SummernoteTextField(blank=True, verbose_name='Вимоги'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Посада'),
        ),
    ]
