# Generated by Django 5.2.14 on 2026-05-25 17:30

import django.db.models.deletion
import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_alter_vacancy_options_alter_vacancy_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['order', '-is_urgent', '-created_at'], 'verbose_name': 'Вакансія', 'verbose_name_plural': 'Вакансії'},
        ),
        migrations.AddField(
            model_name='vacancy',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Велике зображення зверху картки і сторінки. Опціонально.', null=True, upload_to='vacancies/', verbose_name='Головне фото'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='short_tagline',
            field=models.CharField(blank=True, help_text='Один рядок під заголовком (напр., "від 35 000 грн" або "повний бак, гарантія 1 рік").', max_length=200, verbose_name='Короткий підпис'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Місто / Локація'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='conditions',
            field=django_summernote.fields.SummernoteTextField(blank=True, verbose_name='Умови / Комплектація'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='Виділити (термінова / акційна)'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=django_summernote.fields.SummernoteTextField(blank=True, verbose_name='Вимоги / Характеристики'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Посада / Назва'),
        ),
        migrations.CreateModel(
            name='VacancyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vacancies/gallery/', verbose_name='Зображення')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Підпис')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vacancies.vacancy', verbose_name='Вакансія / Товар')),
            ],
            options={
                'verbose_name': 'Фото вакансії',
                'verbose_name_plural': 'Фото вакансій',
                'ordering': ['order'],
            },
        ),
    ]
