# Generated by Django 5.2.14 on 2026-05-25 17:53

import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_alter_vacancy_options_vacancy_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Локація'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='conditions',
            field=django_summernote.fields.SummernoteTextField(blank=True, verbose_name='Умови'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='Виділити'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=django_summernote.fields.SummernoteTextField(blank=True, verbose_name='Вимоги'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='short_tagline',
            field=models.CharField(blank=True, help_text='Один рядок під заголовком.', max_length=200, verbose_name='Короткий підпис'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Заголовок'),
        ),
    ]
