# Generated by Django 5.2.15 on 2026-06-21 16:55

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_sanitize_existing_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Велике зображення зверху картки і сторінки. Опціонально.', null=True, upload_to='vacancies/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.core.validators.validate_image_size], verbose_name='Головне фото'),
        ),
        migrations.AlterField(
            model_name='vacancyimage',
            name='image',
            field=models.ImageField(upload_to='vacancies/gallery/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.core.validators.validate_image_size], verbose_name='Зображення'),
        ),
    ]
