# Generated by Django 5.2.15 on 2026-06-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_alter_vacancy_cover_image_alter_vacancyimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активна'),
        ),
    ]
