# Generated by Django 5.2.15 on 2026-06-22 09:02

import apps.core.validators
import django.core.validators
import django.db.models.deletion
import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_alter_vacancy_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['order', '-is_urgent', '-created_at'], 'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancies'},
        ),
        migrations.AlterModelOptions(
            name='vacancyimage',
            options={'ordering': ['order'], 'verbose_name': 'Vacancy photo', 'verbose_name_plural': 'Vacancy photos'},
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='conditions',
            field=django_summernote.fields.SummernoteTextField(blank=True, verbose_name='Conditions'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Large image at the top of the card and page. Optional.', null=True, upload_to='vacancies/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.core.validators.validate_image_size], verbose_name='Main photo'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=django_summernote.fields.SummernoteTextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='Highlight'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=django_summernote.fields.SummernoteTextField(blank=True, verbose_name='Requirements'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='short_tagline',
            field=models.CharField(blank=True, help_text='A single line under the heading.', max_length=200, verbose_name='Short caption'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='vacancyimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='vacancyimage',
            name='image',
            field=models.ImageField(upload_to='vacancies/gallery/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.core.validators.validate_image_size], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='vacancyimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='vacancyimage',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vacancies.vacancy', verbose_name='Vacancy / Product'),
        ),
    ]
