# Generated by Django 5.2.15 on 2026-06-24 12:32

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0008_alter_vacancy_options_alter_vacancyimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='city_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='city_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='conditions_en',
            field=apps.core.fields.SummernoteTextField(blank=True, null=True, verbose_name='Conditions'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='conditions_uk',
            field=apps.core.fields.SummernoteTextField(blank=True, null=True, verbose_name='Conditions'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_en',
            field=apps.core.fields.SummernoteTextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_uk',
            field=apps.core.fields.SummernoteTextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirements_en',
            field=apps.core.fields.SummernoteTextField(blank=True, null=True, verbose_name='Requirements'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirements_uk',
            field=apps.core.fields.SummernoteTextField(blank=True, null=True, verbose_name='Requirements'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='short_tagline_en',
            field=models.CharField(blank=True, help_text='A single line under the heading.', max_length=200, null=True, verbose_name='Short caption'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='short_tagline_uk',
            field=models.CharField(blank=True, help_text='A single line under the heading.', max_length=200, null=True, verbose_name='Short caption'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_uk',
            field=models.CharField(max_length=300, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='vacancyimage',
            name='caption_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='vacancyimage',
            name='caption_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='conditions',
            field=apps.core.fields.SummernoteTextField(blank=True, verbose_name='Conditions'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=apps.core.fields.SummernoteTextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=apps.core.fields.SummernoteTextField(blank=True, verbose_name='Requirements'),
        ),
    ]
