# Generated by Django 5.2.14 on 2026-05-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(choices=[('site', 'Весь сайт (по умолчанию)'), ('content:home', 'Главная'), ('catalog:product_list', 'Каталог — список товаров'), ('catalog:product_detail', 'Каталог — карточка товара'), ('brands:brand_list', 'Бренды — список'), ('brands:brand_detail', 'Бренды — страница бренда'), ('content:promo_list', 'Акции — список'), ('content:promo_detail', 'Акции — страница акции'), ('content:news_list', 'Новости — список'), ('content:news_detail', 'Новости — страница новости'), ('vacancies:list', 'Вакансии — список'), ('vacancies:detail', 'Вакансии — страница вакансии'), ('contacts:contact', 'Контакты')], default='site', max_length=64, unique=True, verbose_name='Страница')),
                ('image', models.ImageField(upload_to='backgrounds/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('overlay_opacity', models.PositiveSmallIntegerField(default=40, help_text='Прозрачность подложки поверх фона (0–90), чтобы текст оставался читаемым.', verbose_name='Затемнение, %')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Фон страницы',
                'verbose_name_plural': 'Фоны страниц',
                'ordering': ['page_key'],
            },
        ),
    ]
