# Generated by Django 5.2.14 on 2026-05-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagebackground',
            options={'ordering': ['page_key'], 'verbose_name': 'Фон сторінки', 'verbose_name_plural': 'Фони сторінок'},
        ),
        migrations.AlterField(
            model_name='pagebackground',
            name='image',
            field=models.ImageField(upload_to='backgrounds/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='pagebackground',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='pagebackground',
            name='overlay_opacity',
            field=models.PositiveSmallIntegerField(default=40, help_text='Прозорість підкладки поверх фону (0–90), щоб текст залишався читабельним.', verbose_name='Затемнення, %'),
        ),
        migrations.AlterField(
            model_name='pagebackground',
            name='page_key',
            field=models.CharField(choices=[('site', 'Увесь сайт (за замовчуванням)'), ('content:home', 'Головна'), ('catalog:product_list', 'Каталог — список товарів'), ('catalog:product_detail', 'Каталог — картка товару'), ('brands:brand_list', 'Бренди — список'), ('brands:brand_detail', 'Бренди — сторінка бренду'), ('content:promo_list', 'Акції — список'), ('content:promo_detail', 'Акції — сторінка акції'), ('content:news_list', 'Новини — список'), ('content:news_detail', 'Новини — сторінка новини'), ('vacancies:list', 'Вакансії — список'), ('vacancies:detail', 'Вакансії — сторінка вакансії'), ('contacts:contact', 'Контакти')], default='site', max_length=64, unique=True, verbose_name='Сторінка'),
        ),
        migrations.AlterField(
            model_name='pagebackground',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
    ]
