# Generated by Django 5.2.14 on 2026-05-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='anim_cursor_follower',
            field=models.BooleanField(default=False, help_text='Сильний ефект; не для всіх брендів. Вимикається на тач-пристроях автоматично.', verbose_name='Анімація: кастомний кругляк-курсор'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='anim_kinetic_hero',
            field=models.BooleanField(default=True, verbose_name='Анімація: "кінетичне" появлення hero-заголовка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='anim_magnetic_buttons',
            field=models.BooleanField(default=True, help_text='Вимикається на тач-пристроях автоматично.', verbose_name='Анімація: "магнітні" кнопки на hover'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='anim_page_transitions',
            field=models.BooleanField(default=True, help_text='View Transitions API. Працює в Chrome/Edge/Safari; у Firefox без анімації.', verbose_name='Анімація: плавні переходи між сторінками'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='anim_scroll_reveal',
            field=models.BooleanField(default=True, verbose_name='Анімація: появи блоків при прокручуванні (fade-up + stagger)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_eyebrow',
            field=models.CharField(blank=True, help_text='Малий текст над великим заголовком (напр., "Офіційний дистриб\'ютор · 2026").', max_length=80, verbose_name='Hero: верхня плашка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_eyebrow_en',
            field=models.CharField(blank=True, help_text='Малий текст над великим заголовком (напр., "Офіційний дистриб\'ютор · 2026").', max_length=80, null=True, verbose_name='Hero: верхня плашка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_eyebrow_uk',
            field=models.CharField(blank=True, help_text='Малий текст над великим заголовком (напр., "Офіційний дистриб\'ютор · 2026").', max_length=80, null=True, verbose_name='Hero: верхня плашка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.CharField(blank=True, max_length=400, verbose_name='Hero: підзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle_en',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Hero: підзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle_uk',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Hero: підзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(blank=True, help_text='Замінює дефолтний. Для kinetic-ефекту можна підкреслити слово через **слово**.', max_length=200, verbose_name='Hero: великий заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_en',
            field=models.CharField(blank=True, help_text='Замінює дефолтний. Для kinetic-ефекту можна підкреслити слово через **слово**.', max_length=200, null=True, verbose_name='Hero: великий заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_uk',
            field=models.CharField(blank=True, help_text='Замінює дефолтний. Для kinetic-ефекту можна підкреслити слово через **слово**.', max_length=200, null=True, verbose_name='Hero: великий заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_layout',
            field=models.CharField(choices=[('classic', 'Classic (текуща)'), ('editorial', 'Editorial (журнальний — великий типографічний hero)'), ('cinematic', 'Cinematic (повноекранний hero з відео/фото)')], default='editorial', help_text='Стиль hero-секції на головній сторінці.', max_length=20, verbose_name='Макет головної'),
        ),
    ]
