# Generated by Django 5.2.14 on 2026-05-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_anim_cursor_follower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='vacancy_apply_label',
            field=models.CharField(default='Відгукнутися', max_length=80, verbose_name='Вакансія: текст кнопки відгуку'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vacancy_apply_label_en',
            field=models.CharField(default='Відгукнутися', max_length=80, null=True, verbose_name='Вакансія: текст кнопки відгуку'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vacancy_apply_label_uk',
            field=models.CharField(default='Відгукнутися', max_length=80, null=True, verbose_name='Вакансія: текст кнопки відгуку'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vacancy_conditions_label',
            field=models.CharField(default='Умови', max_length=80, verbose_name='Вакансія: заголовок секції "Умови"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vacancy_conditions_label_en',
            field=models.CharField(default='Умови', max_length=80, null=True, verbose_name='Вакансія: заголовок секції "Умови"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vacancy_conditions_label_uk',
            field=models.CharField(default='Умови', max_length=80, null=True, verbose_name='Вакансія: заголовок секції "Умови"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vacancy_description_label',
            field=models.CharField(default='Опис', max_length=80, verbose_name='Вакансія: заголовок секції "Опис"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vacancy_description_label_en',
            field=models.CharField(default='Опис', max_length=80, null=True, verbose_name='Вакансія: заголовок секції "Опис"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vacancy_description_label_uk',
            field=models.CharField(default='Опис', max_length=80, null=True, verbose_name='Вакансія: заголовок секції "Опис"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vacancy_requirements_label',
            field=models.CharField(default='Вимоги', max_length=80, verbose_name='Вакансія: заголовок секції "Вимоги"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vacancy_requirements_label_en',
            field=models.CharField(default='Вимоги', max_length=80, null=True, verbose_name='Вакансія: заголовок секції "Вимоги"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vacancy_requirements_label_uk',
            field=models.CharField(default='Вимоги', max_length=80, null=True, verbose_name='Вакансія: заголовок секції "Вимоги"'),
        ),
    ]
