# Generated by Django 5.2.14 on 2026-05-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_vacancy_apply_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cart_enabled',
            field=models.BooleanField(default=False, help_text='Показувати ціни, кнопки «У кошик» і сторінку кошика. Вмикається пресетом «Магазин». Замовлення надходять у розділ «Замовлення».', verbose_name='Кошик (режим магазину)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cta_label',
            field=models.CharField(default='Зв’язатись', max_length=80, verbose_name='Текст кнопки CTA'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cta_label_en',
            field=models.CharField(default='Зв’язатись', max_length=80, null=True, verbose_name='Текст кнопки CTA'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cta_label_uk',
            field=models.CharField(default='Зв’язатись', max_length=80, null=True, verbose_name='Текст кнопки CTA'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='preset',
            field=models.CharField(choices=[('distributor', "Дистриб'ютор"), ('auto', 'Автосалон'), ('food', 'Їжа / ресторан'), ('shop', 'Магазин (кошик)'), ('generic', 'Універсальний лендінг')], default='distributor', help_text='Тип сайту. Використовується командою apply_preset для заповнення дефолтів.', max_length=20, verbose_name='Пресет (вертикаль)'),
        ),
    ]
