# Generated by Django 5.2.15 on 2026-06-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesettings_contact_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='side_logo_left',
            field=models.ImageField(blank=True, help_text='На широких екранах — закріплене ліворуч (тримається при прокручуванні). На смартфоні — внизу перед футером.', null=True, upload_to='branding/', verbose_name='Бокове лого (ліворуч)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='side_logo_right',
            field=models.ImageField(blank=True, help_text='Те саме, але праворуч / друге лого внизу на смартфоні.', null=True, upload_to='branding/', verbose_name='Бокове лого (праворуч)'),
        ),
    ]
