# Generated by Django 5.2.15 on 2026-06-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesettings_side_logo_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='brand_style',
            field=models.CharField(choices=[('plain', 'Звичайний'), ('gradient', 'Градієнт'), ('underline', 'З підкресленням'), ('script', 'Розписний (курсив)')], default='plain', help_text='Оформлення тексту назви в шапці/футері.', max_length=20, verbose_name='Стиль назви сайту'),
        ),
    ]
