# Generated by Django 5.2.15 on 2026-06-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sitesettings_brand_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='side_logo_size',
            field=models.CharField(choices=[('sm', 'Маленький'), ('md', 'Середній'), ('lg', 'Великий')], default='md', help_text='Розмір бокових лого. На широких екранах — ширина закріплених лого (обмежена бічним полем, щоб не перекривати контент); на смартфоні — висота лого в ряду внизу.', max_length=2, verbose_name='Розмір бокових лого'),
        ),
    ]
