# Generated by Django 5.2.15 on 2026-06-21 16:55

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sitesettings_side_logo_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagebackground',
            name='image',
            field=models.ImageField(upload_to='backgrounds/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.core.validators.validate_image_size], verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'svg']), apps.core.validators.validate_image_size], verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'svg']), apps.core.validators.validate_image_size], verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='side_logo_left',
            field=models.ImageField(blank=True, help_text='На широких екранах — закріплене ліворуч (тримається при прокручуванні). На смартфоні — внизу перед футером.', null=True, upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'svg']), apps.core.validators.validate_image_size], verbose_name='Бокове лого (ліворуч)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='side_logo_right',
            field=models.ImageField(blank=True, help_text='Те саме, але праворуч / друге лого внизу на смартфоні.', null=True, upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'svg']), apps.core.validators.validate_image_size], verbose_name='Бокове лого (праворуч)'),
        ),
    ]
