# Generated by Django 5.2.15 on 2026-06-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_pagebackground_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='brand_name_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='brand_name_uk',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='brand_name',
            field=models.CharField(default='Distributor', max_length=120, verbose_name='Назва сайту'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cta_label',
            field=models.CharField(default='Contact us', max_length=80, verbose_name='Текст кнопки CTA'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cta_label_en',
            field=models.CharField(default='Contact us', max_length=80, null=True, verbose_name='Текст кнопки CTA'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cta_label_uk',
            field=models.CharField(default='Contact us', max_length=80, null=True, verbose_name='Текст кнопки CTA'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_brands_label',
            field=models.CharField(default='Brands', max_length=80, verbose_name='Меню: Бренди — назва'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_brands_label_en',
            field=models.CharField(default='Brands', max_length=80, null=True, verbose_name='Меню: Бренди — назва'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_brands_label_uk',
            field=models.CharField(default='Brands', max_length=80, null=True, verbose_name='Меню: Бренди — назва'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_catalog_label',
            field=models.CharField(default='Catalog', max_length=80, verbose_name='Меню: Каталог — назва'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_catalog_label_en',
            field=models.CharField(default='Catalog', max_length=80, null=True, verbose_name='Меню: Каталог — назва'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_catalog_label_uk',
            field=models.CharField(default='Catalog', max_length=80, null=True, verbose_name='Меню: Каталог — назва'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_contacts_label',
            field=models.CharField(default='Contacts', max_length=80, verbose_name='Меню: Контакти — назва'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_contacts_label_en',
            field=models.CharField(default='Contacts', max_length=80, null=True, verbose_name='Меню: Контакти — назва'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_contacts_label_uk',
            field=models.CharField(default='Contacts', max_length=80, null=True, verbose_name='Меню: Контакти — назва'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_news_label',
            field=models.CharField(default='News', max_length=80, verbose_name='Меню: Новини — назва'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_news_label_en',
            field=models.CharField(default='News', max_length=80, null=True, verbose_name='Меню: Новини — назва'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_news_label_uk',
            field=models.CharField(default='News', max_length=80, null=True, verbose_name='Меню: Новини — назва'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_promos_label',
            field=models.CharField(default='Promotions', max_length=80, verbose_name='Меню: Акції — назва'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_promos_label_en',
            field=models.CharField(default='Promotions', max_length=80, null=True, verbose_name='Меню: Акції — назва'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_promos_label_uk',
            field=models.CharField(default='Promotions', max_length=80, null=True, verbose_name='Меню: Акції — назва'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_vacancies_label',
            field=models.CharField(default='Vacancies', max_length=80, verbose_name='Меню: Вакансії — назва'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_vacancies_label_en',
            field=models.CharField(default='Vacancies', max_length=80, null=True, verbose_name='Меню: Вакансії — назва'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_vacancies_label_uk',
            field=models.CharField(default='Vacancies', max_length=80, null=True, verbose_name='Меню: Вакансії — назва'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_brand_plural',
            field=models.CharField(default='Brands', max_length=80, verbose_name='Термін: бренди (множина)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_brand_plural_en',
            field=models.CharField(default='Brands', max_length=80, null=True, verbose_name='Термін: бренди (множина)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_brand_plural_uk',
            field=models.CharField(default='Brands', max_length=80, null=True, verbose_name='Термін: бренди (множина)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_brand_singular',
            field=models.CharField(default='Brand', max_length=80, verbose_name='Термін: бренд (однина)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_brand_singular_en',
            field=models.CharField(default='Brand', max_length=80, null=True, verbose_name='Термін: бренд (однина)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_brand_singular_uk',
            field=models.CharField(default='Brand', max_length=80, null=True, verbose_name='Термін: бренд (однина)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_category_plural',
            field=models.CharField(default='Categories', max_length=80, verbose_name='Термін: категорії (множина)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_category_plural_en',
            field=models.CharField(default='Categories', max_length=80, null=True, verbose_name='Термін: категорії (множина)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_category_plural_uk',
            field=models.CharField(default='Categories', max_length=80, null=True, verbose_name='Термін: категорії (множина)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_category_singular',
            field=models.CharField(default='Category', max_length=80, verbose_name='Термін: категорія (однина)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_category_singular_en',
            field=models.CharField(default='Category', max_length=80, null=True, verbose_name='Термін: категорія (однина)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_category_singular_uk',
            field=models.CharField(default='Category', max_length=80, null=True, verbose_name='Термін: категорія (однина)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_product_plural',
            field=models.CharField(default='Products', max_length=80, verbose_name='Термін: товари (множина)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_product_plural_en',
            field=models.CharField(default='Products', max_length=80, null=True, verbose_name='Термін: товари (множина)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_product_plural_uk',
            field=models.CharField(default='Products', max_length=80, null=True, verbose_name='Термін: товари (множина)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_product_singular',
            field=models.CharField(default='Product', max_length=80, verbose_name='Термін: товар (однина)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_product_singular_en',
            field=models.CharField(default='Product', max_length=80, null=True, verbose_name='Термін: товар (однина)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_product_singular_uk',
            field=models.CharField(default='Product', max_length=80, null=True, verbose_name='Термін: товар (однина)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vacancy_apply_label',
            field=models.CharField(default='Apply', max_length=80, verbose_name='Вакансія: текст кнопки відгуку'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vacancy_apply_label_en',
            field=models.CharField(default='Apply', max_length=80, null=True, verbose_name='Вакансія: текст кнопки відгуку'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vacancy_apply_label_uk',
            field=models.CharField(default='Apply', max_length=80, null=True, verbose_name='Вакансія: текст кнопки відгуку'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vacancy_conditions_label',
            field=models.CharField(default='Conditions', max_length=80, verbose_name='Вакансія: заголовок секції "Умови"'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vacancy_conditions_label_en',
            field=models.CharField(default='Conditions', max_length=80, null=True, verbose_name='Вакансія: заголовок секції "Умови"'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vacancy_conditions_label_uk',
            field=models.CharField(default='Conditions', max_length=80, null=True, verbose_name='Вакансія: заголовок секції "Умови"'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vacancy_description_label',
            field=models.CharField(default='Description', max_length=80, verbose_name='Вакансія: заголовок секції "Опис"'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vacancy_description_label_en',
            field=models.CharField(default='Description', max_length=80, null=True, verbose_name='Вакансія: заголовок секції "Опис"'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vacancy_description_label_uk',
            field=models.CharField(default='Description', max_length=80, null=True, verbose_name='Вакансія: заголовок секції "Опис"'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vacancy_requirements_label',
            field=models.CharField(default='Requirements', max_length=80, verbose_name='Вакансія: заголовок секції "Вимоги"'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vacancy_requirements_label_en',
            field=models.CharField(default='Requirements', max_length=80, null=True, verbose_name='Вакансія: заголовок секції "Вимоги"'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vacancy_requirements_label_uk',
            field=models.CharField(default='Requirements', max_length=80, null=True, verbose_name='Вакансія: заголовок секції "Вимоги"'),
        ),
    ]
