# Generated by Django 5.2.15 on 2026-06-22 09:02

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_seed_english_sitesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagebackground',
            options={'ordering': ['page_key'], 'verbose_name': 'Page background', 'verbose_name_plural': 'Page backgrounds'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site settings', 'verbose_name_plural': 'Site settings'},
        ),
        migrations.AlterField(
            model_name='pagebackground',
            name='image',
            field=models.ImageField(upload_to='backgrounds/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.core.validators.validate_image_size], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='pagebackground',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='pagebackground',
            name='overlay_opacity',
            field=models.PositiveSmallIntegerField(default=40, help_text='Opacity of the overlay above the background (0–90) to keep text readable.', verbose_name='Overlay, %'),
        ),
        migrations.AlterField(
            model_name='pagebackground',
            name='page_key',
            field=models.CharField(choices=[('site', 'Whole site (default)'), ('content:home', 'Home'), ('catalog:product_list', 'Catalog — product list'), ('catalog:product_detail', 'Catalog — product page'), ('brands:brand_list', 'Brands — list'), ('brands:brand_detail', 'Brands — brand page'), ('content:promo_list', 'Promotions — list'), ('content:promo_detail', 'Promotions — promotion page'), ('content:news_list', 'News — list'), ('content:news_detail', 'News — article page'), ('vacancies:list', 'Vacancies — list'), ('vacancies:detail', 'Vacancies — vacancy page'), ('contacts:contact', 'Contacts')], default='site', max_length=64, unique=True, verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='pagebackground',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='anim_cursor_follower',
            field=models.BooleanField(default=False, help_text='Strong effect; not for every brand. Disabled automatically on touch devices.', verbose_name='Animation: custom dot cursor'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='anim_kinetic_hero',
            field=models.BooleanField(default=True, verbose_name='Animation: kinetic hero title reveal'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='anim_magnetic_buttons',
            field=models.BooleanField(default=True, help_text='Disabled on touch devices automatically.', verbose_name='Animation: magnetic buttons on hover'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='anim_page_transitions',
            field=models.BooleanField(default=True, help_text='View Transitions API. Works in Chrome/Edge/Safari; no animation in Firefox.', verbose_name='Animation: smooth page transitions'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='anim_scroll_reveal',
            field=models.BooleanField(default=True, verbose_name='Animation: scroll reveal (fade-up + stagger)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'svg']), apps.core.validators.validate_image_size], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='brand_name',
            field=models.CharField(default='Distributor', max_length=120, verbose_name='Site name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='brand_style',
            field=models.CharField(choices=[('plain', 'Plain'), ('gradient', 'Gradient'), ('underline', 'Underline'), ('script', 'Script (italic)')], default='plain', help_text='Name text styling in the header/footer.', max_length=20, verbose_name='Site name style'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cart_enabled',
            field=models.BooleanField(default=False, help_text='Show prices, "Add to cart" buttons and the cart page. Enabled by the "Shop" preset. Orders arrive in the "Orders" section.', verbose_name='Cart (shop mode)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Contact email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='Contact phone'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cta_label',
            field=models.CharField(default='Contact us', max_length=80, verbose_name='CTA button text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cta_label_en',
            field=models.CharField(default='Contact us', max_length=80, null=True, verbose_name='CTA button text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cta_label_uk',
            field=models.CharField(default='Contact us', max_length=80, null=True, verbose_name='CTA button text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_copyright',
            field=models.CharField(blank=True, max_length=200, verbose_name='Footer copyright'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_copyright_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Footer copyright'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_copyright_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Footer copyright'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_eyebrow',
            field=models.CharField(blank=True, help_text='Small text above the large heading (e.g., "Official distributor · 2026").', max_length=80, verbose_name='Hero: eyebrow'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_eyebrow_en',
            field=models.CharField(blank=True, help_text='Small text above the large heading (e.g., "Official distributor · 2026").', max_length=80, null=True, verbose_name='Hero: eyebrow'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_eyebrow_uk',
            field=models.CharField(blank=True, help_text='Small text above the large heading (e.g., "Official distributor · 2026").', max_length=80, null=True, verbose_name='Hero: eyebrow'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.CharField(blank=True, max_length=400, verbose_name='Hero: subheading'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle_en',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Hero: subheading'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle_uk',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Hero: subheading'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(blank=True, help_text='Replaces the default. For the kinetic effect, emphasize a word with **word**.', max_length=200, verbose_name='Hero: main heading'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title_en',
            field=models.CharField(blank=True, help_text='Replaces the default. For the kinetic effect, emphasize a word with **word**.', max_length=200, null=True, verbose_name='Hero: main heading'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title_uk',
            field=models.CharField(blank=True, help_text='Replaces the default. For the kinetic effect, emphasize a word with **word**.', max_length=200, null=True, verbose_name='Hero: main heading'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='home_layout',
            field=models.CharField(choices=[('classic', 'Classic (current)'), ('editorial', 'Editorial (magazine — large typographic hero)'), ('cinematic', 'Cinematic (full-screen hero with video/photo)')], default='editorial', help_text='Hero section style on the home page.', max_length=20, verbose_name='Home layout'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='SEO description (default)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='SEO description (default)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description_uk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='SEO description (default)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_brands_label',
            field=models.CharField(default='Brands', max_length=80, verbose_name='Menu: Brands — label'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_brands_label_en',
            field=models.CharField(default='Brands', max_length=80, null=True, verbose_name='Menu: Brands — label'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_brands_label_uk',
            field=models.CharField(default='Brands', max_length=80, null=True, verbose_name='Menu: Brands — label'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_brands_visible',
            field=models.BooleanField(default=True, verbose_name='Menu: Brands — visible'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_catalog_label',
            field=models.CharField(default='Catalog', max_length=80, verbose_name='Menu: Catalog — label'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_catalog_label_en',
            field=models.CharField(default='Catalog', max_length=80, null=True, verbose_name='Menu: Catalog — label'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_catalog_label_uk',
            field=models.CharField(default='Catalog', max_length=80, null=True, verbose_name='Menu: Catalog — label'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_catalog_visible',
            field=models.BooleanField(default=True, verbose_name='Menu: Catalog — visible'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_contacts_label',
            field=models.CharField(default='Contacts', max_length=80, verbose_name='Menu: Contacts — label'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_contacts_label_en',
            field=models.CharField(default='Contacts', max_length=80, null=True, verbose_name='Menu: Contacts — label'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_contacts_label_uk',
            field=models.CharField(default='Contacts', max_length=80, null=True, verbose_name='Menu: Contacts — label'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_contacts_visible',
            field=models.BooleanField(default=False, verbose_name='Menu: Contacts — show'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_news_label',
            field=models.CharField(default='News', max_length=80, verbose_name='Menu: News — label'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_news_label_en',
            field=models.CharField(default='News', max_length=80, null=True, verbose_name='Menu: News — label'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_news_label_uk',
            field=models.CharField(default='News', max_length=80, null=True, verbose_name='Menu: News — label'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_news_visible',
            field=models.BooleanField(default=True, verbose_name='Menu: News — visible'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_promos_label',
            field=models.CharField(default='Promotions', max_length=80, verbose_name='Menu: Promotions — label'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_promos_label_en',
            field=models.CharField(default='Promotions', max_length=80, null=True, verbose_name='Menu: Promotions — label'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_promos_label_uk',
            field=models.CharField(default='Promotions', max_length=80, null=True, verbose_name='Menu: Promotions — label'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_promos_visible',
            field=models.BooleanField(default=True, verbose_name='Menu: Promotions — show'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_vacancies_label',
            field=models.CharField(default='Vacancies', max_length=80, verbose_name='Menu: Vacancies — label'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_vacancies_label_en',
            field=models.CharField(default='Vacancies', max_length=80, null=True, verbose_name='Menu: Vacancies — label'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_vacancies_label_uk',
            field=models.CharField(default='Vacancies', max_length=80, null=True, verbose_name='Menu: Vacancies — label'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_vacancies_visible',
            field=models.BooleanField(default=True, verbose_name='Menu: Vacancies — visible'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='preset',
            field=models.CharField(choices=[('distributor', 'Distributor'), ('auto', 'Auto dealership'), ('food', 'Food / restaurant'), ('shop', 'Shop (cart)'), ('generic', 'Generic landing')], default='distributor', help_text='Site type. Used by the apply_preset command to fill defaults.', max_length=20, verbose_name='Preset (vertical)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='side_logo_left',
            field=models.ImageField(blank=True, help_text='On wide screens — pinned to the left (stays while scrolling). On mobile — below the content, before the footer.', null=True, upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'svg']), apps.core.validators.validate_image_size], verbose_name='Side logo (left)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='side_logo_right',
            field=models.ImageField(blank=True, help_text='Same as left, but on the right / second logo at the bottom on mobile.', null=True, upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'svg']), apps.core.validators.validate_image_size], verbose_name='Side logo (right)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='side_logo_size',
            field=models.CharField(choices=[('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large')], default='md', help_text="Side logo size. On wide screens — the width of the pinned logos (constrained by the side margin so they don't overlap content); on mobile — the height of the logos in the bottom row.", max_length=2, verbose_name='Side logo size'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(blank=True, max_length=300, verbose_name='Tagline'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Tagline'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline_uk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Tagline'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_brand_plural',
            field=models.CharField(default='Brands', max_length=80, verbose_name='Term: brands (plural)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_brand_plural_en',
            field=models.CharField(default='Brands', max_length=80, null=True, verbose_name='Term: brands (plural)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_brand_plural_uk',
            field=models.CharField(default='Brands', max_length=80, null=True, verbose_name='Term: brands (plural)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_brand_singular',
            field=models.CharField(default='Brand', max_length=80, verbose_name='Term: brand (singular)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_brand_singular_en',
            field=models.CharField(default='Brand', max_length=80, null=True, verbose_name='Term: brand (singular)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_brand_singular_uk',
            field=models.CharField(default='Brand', max_length=80, null=True, verbose_name='Term: brand (singular)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_category_plural',
            field=models.CharField(default='Categories', max_length=80, verbose_name='Term: categories (plural)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_category_plural_en',
            field=models.CharField(default='Categories', max_length=80, null=True, verbose_name='Term: categories (plural)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_category_plural_uk',
            field=models.CharField(default='Categories', max_length=80, null=True, verbose_name='Term: categories (plural)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_category_singular',
            field=models.CharField(default='Category', max_length=80, verbose_name='Term: category (singular)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_category_singular_en',
            field=models.CharField(default='Category', max_length=80, null=True, verbose_name='Term: category (singular)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_category_singular_uk',
            field=models.CharField(default='Category', max_length=80, null=True, verbose_name='Term: category (singular)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_product_plural',
            field=models.CharField(default='Products', max_length=80, verbose_name='Term: products (plural)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_product_plural_en',
            field=models.CharField(default='Products', max_length=80, null=True, verbose_name='Term: products (plural)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_product_plural_uk',
            field=models.CharField(default='Products', max_length=80, null=True, verbose_name='Term: products (plural)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_product_singular',
            field=models.CharField(default='Product', max_length=80, verbose_name='Term: product (singular)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_product_singular_en',
            field=models.CharField(default='Product', max_length=80, null=True, verbose_name='Term: product (singular)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='term_product_singular_uk',
            field=models.CharField(default='Product', max_length=80, null=True, verbose_name='Term: product (singular)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='theme',
            field=models.CharField(choices=[('classic', 'Classic (light blue)'), ('cyberpunk', 'Cyberpunk (neon)'), ('nude', 'Nude (pastel)'), ('darklux', 'Dark Lux (premium dark)')], default='classic', max_length=20, verbose_name='Theme'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vacancy_apply_label',
            field=models.CharField(default='Apply', max_length=80, verbose_name='Vacancy: apply button text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vacancy_apply_label_en',
            field=models.CharField(default='Apply', max_length=80, null=True, verbose_name='Vacancy: apply button text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vacancy_apply_label_uk',
            field=models.CharField(default='Apply', max_length=80, null=True, verbose_name='Vacancy: apply button text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vacancy_conditions_label',
            field=models.CharField(default='Conditions', max_length=80, verbose_name='Vacancy: "Conditions" section heading'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vacancy_conditions_label_en',
            field=models.CharField(default='Conditions', max_length=80, null=True, verbose_name='Vacancy: "Conditions" section heading'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vacancy_conditions_label_uk',
            field=models.CharField(default='Conditions', max_length=80, null=True, verbose_name='Vacancy: "Conditions" section heading'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vacancy_description_label',
            field=models.CharField(default='Description', max_length=80, verbose_name='Vacancy: "Description" section heading'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vacancy_description_label_en',
            field=models.CharField(default='Description', max_length=80, null=True, verbose_name='Vacancy: "Description" section heading'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vacancy_description_label_uk',
            field=models.CharField(default='Description', max_length=80, null=True, verbose_name='Vacancy: "Description" section heading'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vacancy_requirements_label',
            field=models.CharField(default='Requirements', max_length=80, verbose_name='Vacancy: "Requirements" section heading'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vacancy_requirements_label_en',
            field=models.CharField(default='Requirements', max_length=80, null=True, verbose_name='Vacancy: "Requirements" section heading'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vacancy_requirements_label_uk',
            field=models.CharField(default='Requirements', max_length=80, null=True, verbose_name='Vacancy: "Requirements" section heading'),
        ),
    ]
