# Generated by Django 5.2.15 on 2026-06-30 20:22

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_pagebackground_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagebackground',
            name='position',
            field=models.CharField(choices=[('center', 'Center'), ('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right'), ('top left', 'Top-left'), ('top right', 'Top-right'), ('bottom left', 'Bottom-left'), ('bottom right', 'Bottom-right')], default='center', max_length=20, verbose_name='Background position'),
        ),
        migrations.AddField(
            model_name='pagebackground',
            name='size',
            field=models.CharField(choices=[('cover', 'Cover (fill)'), ('contain', 'Contain (fit)')], default='cover', max_length=10, verbose_name='Background size'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chrome_bg',
            field=colorfield.fields.ColorField(blank=True, default='', help_text='Overrides the header & footer background. Empty = theme default.', image_field=None, max_length=25, samples=None, verbose_name='Header/footer background'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chrome_opacity',
            field=models.PositiveSmallIntegerField(default=100, help_text='100 = solid, lower = more transparent.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Header/footer opacity, %'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chrome_text',
            field=colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=25, samples=None, verbose_name='Header/footer text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='custom_accent',
            field=colorfield.fields.ColorField(blank=True, default='', help_text="Overrides the theme's primary colour. Empty = use the selected theme.", image_field=None, max_length=25, samples=None, verbose_name='Custom accent colour'),
        ),
    ]
