# Generated by Django 5.2.15 on 2026-07-06 21:53

import apps.core.validators
import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_pagebackground_position_pagebackground_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagebackground',
            name='color_1',
            field=colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=25, samples=None, verbose_name='Colour 1'),
        ),
        migrations.AddField(
            model_name='pagebackground',
            name='color_2',
            field=colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=25, samples=None, verbose_name='Colour 2'),
        ),
        migrations.AddField(
            model_name='pagebackground',
            name='color_3',
            field=colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=25, samples=None, verbose_name='Colour 3'),
        ),
        migrations.AddField(
            model_name='pagebackground',
            name='kind',
            field=models.CharField(choices=[('image', 'Image (static photo)'), ('gradient', 'Animated gradient'), ('aurora', 'Aurora (soft drifting glow)'), ('particles', 'Particles (interactive network)')], default='image', help_text="Animated types use the colours below (empty = the theme's accent).", max_length=12, verbose_name='Background type'),
        ),
        migrations.AddField(
            model_name='pagebackground',
            name='speed',
            field=models.PositiveSmallIntegerField(default=100, help_text='100 = normal. Lower is slower and calmer, higher is faster.', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(300)], verbose_name='Animation speed, %'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='corner_style',
            field=models.CharField(choices=[('none', 'None (sharp corners)'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xlarge', 'Extra large'), ('2xlarge', '2× extra large'), ('3xlarge', '3× extra large (default)'), ('full', 'Full (pill buttons)')], default='3xlarge', help_text='Roundness of cards, buttons and inputs across the site.', max_length=10, verbose_name='Corner rounding'),
        ),
        migrations.AlterField(
            model_name='pagebackground',
            name='image',
            field=models.ImageField(blank=True, help_text='Required for the “Image” type; ignored otherwise.', upload_to='backgrounds/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.core.validators.validate_image_size], verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='ElementStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(choices=[('site', 'Whole site (default)'), ('content:home', 'Home'), ('catalog:product_list', 'Catalog — product list'), ('catalog:product_detail', 'Catalog — product page'), ('brands:brand_list', 'Brands — list'), ('brands:brand_detail', 'Brands — brand page'), ('content:promo_list', 'Promotions — list'), ('content:promo_detail', 'Promotions — promotion page'), ('content:news_list', 'News — list'), ('content:news_detail', 'News — article page'), ('vacancies:list', 'Vacancies — list'), ('vacancies:detail', 'Vacancies — vacancy page'), ('contacts:contact', 'Contacts')], default='site', help_text='“Whole site” applies everywhere; a page-specific style overrides it.', max_length=64, verbose_name='Page')),
                ('element_key', models.CharField(choices=[('navbar', 'Navbar (header)'), ('navbar-brand', 'Navbar — brand (logo + name)'), ('navbar-menu', 'Navbar — menu links'), ('navbar-cta', 'Navbar — CTA button'), ('hero', 'Hero — whole section'), ('hero-eyebrow', 'Hero — eyebrow (small text above title)'), ('hero-title', 'Hero — main title'), ('hero-subtitle', 'Hero — subtitle'), ('hero-actions', 'Hero — action buttons'), ('hero-collage', 'Hero — banner collage strip'), ('section-brands', 'Home — brands section'), ('section-promos', 'Home — promotions section'), ('section-featured', 'Home — featured products section'), ('section-news', 'Home — news section'), ('section-heading', 'Section headings (h2)'), ('page-title', 'Page title (h1 on inner pages)'), ('card-product', 'Product card'), ('card-promo', 'Promo card'), ('card-news', 'News card'), ('filters', 'Catalog — filters panel'), ('pagination', 'Pagination'), ('content-body', 'Main content area'), ('side-logos', 'Side logos'), ('footer', 'Footer'), ('footer-brand', 'Footer — brand block'), ('contact-form', 'Contact form'), ('cta-button', 'All primary buttons')], max_length=40, verbose_name='Element')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('text_color', colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=25, samples=None, verbose_name='Text colour')),
                ('bg_color', colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=25, samples=None, verbose_name='Background colour')),
                ('opacity', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Opacity, %')),
                ('font_size', models.PositiveSmallIntegerField(blank=True, help_text='Empty = theme size.', null=True, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(200)], verbose_name='Font size, px')),
                ('text_align', models.CharField(blank=True, choices=[('', 'Theme default'), ('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='', max_length=6, verbose_name='Text alignment')),
                ('offset_x', models.SmallIntegerField(default=0, help_text='Positive = right, negative = left.', validators=[django.core.validators.MinValueValidator(-500), django.core.validators.MaxValueValidator(500)], verbose_name='Shift right/left, px')),
                ('offset_y', models.SmallIntegerField(default=0, help_text='Positive = down, negative = up.', validators=[django.core.validators.MinValueValidator(-500), django.core.validators.MaxValueValidator(500)], verbose_name='Shift down/up, px')),
                ('scale', models.PositiveSmallIntegerField(default=100, help_text='Visual zoom of the element. 100 = normal size.', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(300)], verbose_name='Size (scale), %')),
                ('max_width', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(3000)], verbose_name='Max width, px')),
                ('border_radius', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(200)], verbose_name='Corner radius, px')),
                ('padding', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(300)], verbose_name='Inner padding, px')),
                ('hidden', models.BooleanField(default=False, help_text='Removes the element from the page entirely.', verbose_name='Hide element')),
                ('effect', models.CharField(blank=True, choices=[('', 'None'), ('float', 'Float (gentle up/down)'), ('pulse', 'Pulse (breathing)'), ('fade-in', 'Fade in on load'), ('slide-up', 'Slide up on load')], default='', max_length=10, verbose_name='Animation')),
                ('custom_css', models.TextField(blank=True, default='', help_text='Extra CSS declarations, e.g. “letter-spacing: 2px; text-transform: uppercase;”', validators=[apps.core.validators.validate_css_declarations], verbose_name='Extra CSS (advanced)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Element style',
                'verbose_name_plural': 'Element styles (constructor)',
                'ordering': ['page_key', 'element_key'],
                'constraints': [models.UniqueConstraint(fields=('page_key', 'element_key'), name='unique_elementstyle_per_page_element')],
            },
        ),
    ]
