# Generated by Django 5.2.15 on 2026-07-07 10:26

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_pagebackground_color_1_pagebackground_color_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagebackground',
            name='custom_config',
            field=models.TextField(blank=True, default='', help_text='For the “Custom” type: a tsparticles options object (JSON). See https://particles.js.org for examples — paste any preset here.', validators=[apps.core.validators.validate_json_object], verbose_name='Custom background config (JSON)'),
        ),
        migrations.AlterField(
            model_name='pagebackground',
            name='kind',
            field=models.CharField(choices=[('image', 'Image (static photo)'), ('gradient', 'Animated gradient'), ('aurora', 'Aurora (soft drifting glow)'), ('waves', 'Waves (flowing bands)'), ('particles', 'Particles (interactive network)'), ('bubbles', 'Bubbles (floating up)'), ('snow', 'Snow (falling flakes)'), ('stars', 'Stars (twinkling)'), ('custom', 'Custom (own tsparticles JSON config)')], default='image', help_text="Animated types use the colours below (empty = the theme's accent).", max_length=12, verbose_name='Background type'),
        ),
    ]
