# Generated by Django 5.2.14 on 2026-05-30 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('in_stock', 'В наявності'), ('on_order', 'Під замовлення'), ('reserved', 'Зарезервовано'), ('sold', 'Продано')], default='in_stock', max_length=20, verbose_name='Наявність'),
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('UAH', 'грн'), ('USD', '$'), ('EUR', '€')], default='UAH', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, max_length=120, verbose_name='Місто / локація'),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Заповніть, щоб показати знижку (закреслена стара ціна).', max_digits=12, null=True, verbose_name='Стара ціна'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brands/logos/', verbose_name='Логотип'),
        ),
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, verbose_name='Назва параметра')),
                ('value', models.CharField(max_length=255, verbose_name='Значення')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметри',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VehicleSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Рік випуску')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Пробіг, км')),
                ('fuel_type', models.CharField(blank=True, choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('hybrid', 'Гібрид'), ('electric', 'Електро'), ('gas', 'Газ / бензин')], max_length=20, verbose_name='Тип палива')),
                ('transmission', models.CharField(blank=True, choices=[('manual', 'Механіка'), ('automatic', 'Автомат'), ('robot', 'Робот'), ('cvt', 'Варіатор')], max_length=20, verbose_name='Коробка передач')),
                ('engine_volume', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name="Об'єм двигуна, л")),
                ('power', models.PositiveIntegerField(blank=True, null=True, verbose_name='Потужність, к.с.')),
                ('color', models.CharField(blank=True, max_length=60, verbose_name='Колір')),
                ('condition', models.CharField(choices=[('new', 'Нове'), ('used', 'Вживане')], default='used', max_length=10, verbose_name='Стан')),
                ('vin', models.CharField(blank=True, max_length=17, verbose_name='VIN')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='catalog.product', verbose_name='Авто')),
            ],
            options={
                'verbose_name': 'Характеристики авто',
                'verbose_name_plural': 'Характеристики авто',
            },
        ),
    ]
