# Generated by Django 5.2.15 on 2026-06-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='brand',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='location_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='City / location'),
        ),
        migrations.AddField(
            model_name='product',
            name='location_uk',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='City / location'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uk',
            field=models.CharField(max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='productspec',
            name='label_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Parameter name'),
        ),
        migrations.AddField(
            model_name='productspec',
            name='label_uk',
            field=models.CharField(max_length=120, null=True, verbose_name='Parameter name'),
        ),
        migrations.AddField(
            model_name='productspec',
            name='value_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Value'),
        ),
        migrations.AddField(
            model_name='productspec',
            name='value_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Value'),
        ),
        migrations.AddField(
            model_name='vehiclespec',
            name='color_en',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='vehiclespec',
            name='color_uk',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Color'),
        ),
    ]
