# Generated by Django 5.2.14 on 2026-05-16 21:18

import django.db.models.deletion
import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial_catalog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Заголовок")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Подзаголовок"
                    ),
                ),
                (
                    "background",
                    models.ImageField(upload_to="banners/", verbose_name="Фон"),
                ),
                (
                    "button_text",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Текст кнопки"
                    ),
                ),
                (
                    "button_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Ссылка кнопки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Баннер",
                "verbose_name_plural": "Баннеры",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=400, verbose_name="Заголовок")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=400, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "preview",
                    models.TextField(max_length=500, verbose_name="Краткое описание"),
                ),
                (
                    "content",
                    django_summernote.fields.SummernoteTextField(
                        verbose_name="Полный текст"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="news/", verbose_name="Изображение"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Опубликована"),
                ),
                ("published_at", models.DateTimeField(verbose_name="Дата публикации")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="Promo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=400, verbose_name="Заголовок")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=400, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "description",
                    django_summernote.fields.SummernoteTextField(
                        verbose_name="Описание"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="promos/", verbose_name="Изображение"),
                ),
                (
                    "date_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="Начало акции"
                    ),
                ),
                (
                    "date_end",
                    models.DateField(blank=True, null=True, verbose_name="Конец акции"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.brand",
                        verbose_name="Бренд",
                    ),
                ),
            ],
            options={
                "verbose_name": "Акция",
                "verbose_name_plural": "Акции",
                "ordering": ["-date_start"],
            },
        ),
    ]
