# Generated by Django 5.2.14 on 2026-05-18 19:08

import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['order'], 'verbose_name': 'Банер', 'verbose_name_plural': 'Банери'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_at'], 'verbose_name': 'Новина', 'verbose_name_plural': 'Новини'},
        ),
        migrations.AlterModelOptions(
            name='promo',
            options={'ordering': ['-date_start'], 'verbose_name': 'Акція', 'verbose_name_plural': 'Акції'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Посилання кнопки'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500, verbose_name='Підзаголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=django_summernote.fields.SummernoteTextField(verbose_name='Повний текст'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Опублікована'),
        ),
        migrations.AlterField(
            model_name='news',
            name='preview',
            field=models.TextField(max_length=500, verbose_name='Короткий опис'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(verbose_name='Дата публікації'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Кінець акції'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Початок акції'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='description',
            field=django_summernote.fields.SummernoteTextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='image',
            field=models.ImageField(upload_to='promos/', verbose_name='Зображення'),
        ),
    ]
