# Generated by Django 5.2.15 on 2026-06-21 16:55

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_sanitize_existing_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='background',
            field=models.ImageField(upload_to='banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.core.validators.validate_image_size], verbose_name='Фон'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.core.validators.validate_image_size], verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='image',
            field=models.ImageField(upload_to='promos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.core.validators.validate_image_size], verbose_name='Зображення'),
        ),
    ]
