# Generated by Django 5.2.15 on 2026-06-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_banner_background_alter_news_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Опублікована'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активна'),
        ),
    ]
