# Generated by Django 5.2.15 on 2026-06-22 09:02

import apps.core.validators
import django.core.validators
import django.db.models.deletion
import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_brand_options_alter_category_options_and_more'),
        ('content', '0005_alter_banner_is_active_alter_news_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['order'], 'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_at'], 'verbose_name': 'News item', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='promo',
            options={'ordering': ['-date_start'], 'verbose_name': 'Promotion', 'verbose_name_plural': 'Promotions'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='background',
            field=models.ImageField(upload_to='banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.core.validators.validate_image_size], verbose_name='Background'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Button text'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Button URL'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=django_summernote.fields.SummernoteTextField(verbose_name='Full text'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.core.validators.validate_image_size], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='news',
            name='preview',
            field=models.TextField(max_length=500, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(verbose_name='Published at'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=400, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Promotion end'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Promotion start'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='description',
            field=django_summernote.fields.SummernoteTextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='image',
            field=models.ImageField(upload_to='promos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.core.validators.validate_image_size], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='title',
            field=models.CharField(max_length=400, verbose_name='Title'),
        ),
    ]
