# Generated by Django 5.2.15 on 2026-06-24 12:32

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_banner_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button_text_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Button text'),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_text_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Button text'),
        ),
        migrations.AddField(
            model_name='banner',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='banner',
            name='subtitle_uk',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_uk',
            field=models.CharField(max_length=300, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=apps.core.fields.SummernoteTextField(null=True, verbose_name='Full text'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_uk',
            field=apps.core.fields.SummernoteTextField(null=True, verbose_name='Full text'),
        ),
        migrations.AddField(
            model_name='news',
            name='preview_en',
            field=models.TextField(max_length=500, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='news',
            name='preview_uk',
            field=models.TextField(max_length=500, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=400, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uk',
            field=models.CharField(max_length=400, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='promo',
            name='description_en',
            field=apps.core.fields.SummernoteTextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='promo',
            name='description_uk',
            field=apps.core.fields.SummernoteTextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='promo',
            name='title_en',
            field=models.CharField(max_length=400, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='promo',
            name='title_uk',
            field=models.CharField(max_length=400, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=apps.core.fields.SummernoteTextField(verbose_name='Full text'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='description',
            field=apps.core.fields.SummernoteTextField(verbose_name='Description'),
        ),
    ]
